name: Test

on:
  push:
  pull_request:

jobs:
  validate-data:
    env:
      REMOTE_CONTROL_BOT_TOKEN: ${{ secrets.REMOTE_CONTROL_BOT_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Validate workflows
        run: |
          npm i
          npm test
