name: Test

on:
  push:
  pull_request:

jobs:
  validate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Validate workflows
        run: |
          npm i
          npx test
        working-directory: .
